name: Amazon Bot

on:
  schedule:
    - cron: "0 8,12,16,20 * * *"  # 4 volte al giorno
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
          AMAZON_COUNTRY: ${{ secrets.AMAZON_COUNTRY }}
          BITLY_TOKEN: ${{ secrets.BITLY_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
          ITEM_COUNT: ${{ secrets.ITEM_COUNT }}
          MIN_SAVE: ${{ secrets.MIN_SAVE }}
          RUN_ONCE: ${{ secrets.RUN_ONCE }}
        run: python main.py
