name: Zamzam Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"  # ogni 30 minuti

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install python-amazon-paapi python-telegram-bot

      - name: Verifica python-amazon-paapi
        run: |
          python -c "import amazon.paapi; print('python-amazon-paapi installato correttamente!')"

      - name: Esegui bot
        run: python main.py
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
          AMAZON_COUNTRY: ${{ secrets.AMAZON_COUNTRY }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
          MIN_SAVE: ${{ secrets.MIN_SAVE }}
          ITEM_COUNT: ${{ secrets.ITEM_COUNT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DRY_RUN: ${{ secrets.DRY_RUN }}
