name: Run Zamzam Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # Tutti i giorni alle 8:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Export dependencies
      run: |
        pip freeze > requirements.txt
        pip freeze > pip_freeze.txt

    - name: Commit updated requirements.txt
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add requirements.txt
        git commit -m "Update requirements.txt [skip ci]" || echo "No changes to commit"
        git push

    - name: Upload dependency artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dependency-files
        path: pip_freeze.txt

    - name: Run bot
      run: python main.py
      env:
        AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
        AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
        AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
        AMAZON_COUNTRY: ${{ secrets.AMAZON_COUNTRY }}
        BITLY_TOKEN: ${{ secrets.BITLY_TOKEN }}
        ITEM_COUNT: ${{ secrets.ITEM_COUNT }}
        KEYWORDS: ${{ secrets.KEYWORDS }}
        MIN_SAVE: ${{ secrets.MIN_SAVE }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        RUN_ONCE: ${{ secrets.RUN_ONCE }}
