name: Run Zamzam Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # Esempio: tutti i giorni alle 8:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug installed packages
      run: |
        pip list
        pip freeze > pip_freeze.txt

    - name: Upload pip freeze artifact
      uses: actions/upload-artifact@v4
      with:
        name: pip-freeze-output
        path: pip_freeze.txt

    - name: Run bot
      run: python main.py
      env:
        AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
        AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
        AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
        AMAZON_COUNTRY: ${{ secrets.AMAZON_COUNTRY }}
        BITLY_TOKEN: ${{ secrets.BITLY_TOKEN }}
        ITEM_COUNT: ${{ secrets.ITEM_COUNT }}
        KEYWORDS: ${{ secrets.KEYWORDS }}
        MIN_SAVE: ${{ secrets.MIN_SAVE }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        RUN_ONCE: ${{ secrets.RUN_ONCE }}
