name: Run Amazon Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # ogni 6 ore

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
          AMAZON_COUNTRY: ${{ secrets.AMAZON_COUNTRY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ITEM_COUNT: ${{ secrets.ITEM_COUNT }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
          MIN_SAVE: ${{ secrets.MIN_SAVE }}
          RUN_ONCE: ${{ secrets.RUN_ONCE }}
        run: python main.py

      - name: Upload debug file
        uses: actions/upload-artifact@v3
        with:
          name: amazon_debug
          path: amazon_debug.json

      - name: Upload raw API response
        uses: actions/upload-artifact@v3
        with:
          name: amazon_raw_response
          path: amazon_raw_response.json
