name: Run Zamzam Bot

on:
  push:
    branches:
      - main
  workflow_dispatch: # permette di farlo partire manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run bot
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
          AMAZON_COUNTRY: ${{ secrets.AMAZON_COUNTRY }}
          BITLY_TOKEN: ${{ secrets.BITLY_TOKEN }}
          ITEM_COUNT: ${{ secrets.ITEM_COUNT }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
          MIN_SAVE: ${{ secrets.MIN_SAVE }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RUN_ONCE: ${{ secrets.RUN_ONCE }}
        run: python main.py
