name: Post Amazon Deal (every 30 minutes)

on:
  schedule:
    - cron: '*/30 * * * *'   # ogni 30 minuti (UTC)
  workflow_dispatch:         # esegui manualmente per test

jobs:
  post-deal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
          AMAZON_COUNTRY: ${{ secrets.AMAZON_COUNTRY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          KEYWORDS: ${{ secrets.KEYWORDS }}    # opzionale
          MIN_SAVE: ${{ secrets.MIN_SAVE }}    # opzionale
        run: python main.py
