name: Update Requirements and Run Bot

on:
  schedule:
    - cron: '0 2 * * *' # Ogni giorno alle 02:00
  workflow_dispatch: # Avvio manuale

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Aggiorna requirements.txt
        run: |
          pip install --upgrade -r requirements.txt
          pip freeze > requirements.txt

      - name: Salva elenco pacchetti (pip_freeze.txt)
        run: pip freeze > pip_freeze.txt

      - name: Commit e push modifiche
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add requirements.txt pip_freeze.txt
          git commit -m "Aggiornamento automatico pacchetti" || echo "Nessuna modifica da committare"
          git push

      - name: Avvia il bot
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
          AMAZON_COUNTRY: ${{ secrets.AMAZON_COUNTRY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          BITLY_TOKEN: ${{ secrets.BITLY_TOKEN }}
          ITEM_COUNT: ${{ secrets.ITEM_COUNT }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
          MIN_SAVE: ${{ secrets.MIN_SAVE }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RUN_ONCE: ${{ secrets.RUN_ONCE }}
        run: python main.py
