name: Run Amazon Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6,12,18 * * *'  # Pubblica 3 volte al giorno (mattina, pomeriggio, sera)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade amazon-paapi5  # Forziamo l'installazione del modulo specifico
          pip install -r requirements.txt
          
      - name: Run bot
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
          AMAZON_COUNTRY: ${{ secrets.AMAZON_COUNTRY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MIN_DISCOUNT: ${{ secrets.MIN_DISCOUNT }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
          ITEM_COUNT: ${{ secrets.ITEM_COUNT }}
        run: |
          python main.py
