name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"  # ogni 4 ore

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run bot
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_ASSOCIATE_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}
          AMAZON_COUNTRY: ${{ secrets.AMAZON_COUNTRY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          BITLY_TOKEN: ${{ secrets.BITLY_TOKEN }}
          ITEM_COUNT: ${{ secrets.ITEM_COUNT }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
          MIN_SAVE: ${{ secrets.MIN_SAVE }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RUN_ONCE: ${{ secrets.RUN_ONCE }}
        run: python run-bot.py
